services:
  database:
    image: postgres:16
    container_name: fkmtime-app-database
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fkm_time_app
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 5s
      timeout: 20s
      retries: 50
  
  dummy_wca:
    container_name: fkmtime-app-dummy-wca
    restart: unless-stopped
    image: maxidragon/dummy-wca:main
    ports:
      - "3005:3000"

volumes:
  database: